### ISSUE TITLE
Cloned campaign not any events

### ISSUE THREAD

**Issue by smartyaunt** [mautic/api-library#253] opened 2021-06-13 15:36 UTC
mautic version: 3.3.3
php version: 7.4

Cloned campaign will not show any events, 
but if I go to clone through the UI page, it work. Can anyone help me?

**Comment by RCheesley** [comment] 2021-06-13 16:07
This appears to be a duplicate of https://github.com/mautic/mautic/issues/8376

**Closed** 2021-06-13 16:07 UTC
